version: '2'

services:

    # btc is an image of bitcoin node which used as base image for btcd and
    # btccli. The environment variables default values determined on stage of
    # container start within starting script.
    btc:
      image: btcd
      build:
        context: btcd/
      volumes:
            - shared:/rpc
            - bitcoin:/data
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK

    btcd:
        extends: btc
        container_name: btcd
        environment:
          - DEBUG
          - MINING_ADDRESS
        entrypoint: ["./start-btcd.sh"]

    btcctl:
        extends: btc
        container_name: btcctl
        links:
            - "btcd:rpcserver"
        entrypoint: ["./start-btcctl.sh"]

    #
    # lnd - lightening daemon
    # 

    lnd:
        image: lnd
        build:
          context: ../
          dockerfile: docker/lnd/Dockerfile
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG
        volumes:
            - shared:/rpc
        entrypoint: ["./start-lnd.sh"]

    lnd_btc:
      extends: lnd
      container_name: lnd_btc
      links:
          - "btcd:blockchain"


    clightning:
       image: elementsproject/lightningd
       container_name: lightningd
       command:
         - --bitcoin-rpcconnect=bitcoind
         - --bitcoin-rpcuser=rpcuser
         - --bitcoin-rpcpassword=rpcpass
         - --network=bitcoin
         - --alias=mybongistan
         - --log-level=debug
       environment:
         EXPOSE_TCP: "true"
       expose:
         - "9735"
       ports:
         - "0.0.0.0:9735:9735"
       volumes:
         - "lightning:/root/.lightning"
         - "bitcoin:/etc/bitcoin"
         - shared:/rpc
       links:
         - btcd


volumes:
  # shared volume is need to store the btcd rpc certificates and use it within
  # btcctl and lnd containers.
  shared:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/run/media/florian/ZEUS_USBG3_1TERRA/shared'

  # bitcoin volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  bitcoin:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/run/media/florian/ZEUS_USBG3_1TERRA/bitcoin'


  # lightening daemon
  lightning:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/run/media/florian/ZEUS_USBG3_1TERRA/lightening'

