version: '2'

services:

    # btc is an image of bitcoin node which used as base image for btcd and
    # btccli. The environment variables default values determined on stage of
    # container start within starting script.
    bitcoind:
      image: bitcoind
      container_name: bitcoind
      build:
        context: ../
        dockerfile: docker/bitcoind/Dockerfile
      volumes:
            - shared:/rpc
            - bitcoind:/root/.bitcoin
      environment:
        - BTC_RPCUSER
        - BTC_RPCPASSWORD
        - BTC_TXINDEX=1
        - MINING_ADDRESS
      entrypoint: ["/usr/local/bin/docker_entrypoint.sh"]
      ports:
          - "8332:8332"
          - "8333:8333"

    #
    # lnd - lightening daemon
    # 

    lnd:
        image: lnd
        container_name: lnd
        build:
          context: ../
          dockerfile: docker/lnd/Dockerfile
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG
        volumes:
          - shared:/rpc
          - lnd:/root/.lnd
        depends_on:
          - bitcoind
        links:
          - "bitcoind:bitcoind"
        ports:
          - "8089:8089"
          - "10001:10001"
          - "10011:10011"
       
        # expose is not visible from the host
        #expose:
        #  - "8089"
        #  - "10001"
        #  - "10011"
        entrypoint: ["./start-lnd.sh"]
  

    nodeapp:
        image: nodeapp
        container_name: nodeapp
        build:
          context: nodeapp/
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG
        volumes:
            - shared:/rpc
            - lnd:/root/.lnd
        # HOST:CONTAINER
        ports:
           - "80:8088"
        links:
          - "lnd:lnd"
        depends_on:
          - lnd

    rtl:
        image: rtl
        container_name: rtl
        build:
          context: rtl/
        environment:
          LND_SERVER_URL: http://lnd:8089/v1
          MACAROON_PATH: /lnd/data/chain/bitcoin/mainnet
          LND_CONFIG_PATH: /RTL/lnd.conf
          #RTL_CONFIG_PATH: /RTL/RTL.conf
          BITCOIND_CONFIG_PATH: /bitcoind/bitcoin.conf
          RTL_SSO: 1
          RTL_COOKIE_PATH: /RTL/.cookie
          LOGOUT_REDIRECT_LINK: /server/services
        volumes:
            - lnd:/lnd
            - rtl:/rtldata
            - bitcoind:/bitcoind
        # HOST:CONTAINER
        ports:
           - "3000:3000"
        links:
          - "lnd:lnd"
        depends_on:
          - lnd
        entrypoint: ["./start-rtl.sh"]

        # expose only works in containers networks; not visible from host
        # expose:
        #  - "8088"

volumes:
  # shared volume is need to store the btcd rpc certificates and use it within
  # btcctl and lnd containers.
  shared:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/datadrive/shared'

  # bitcoin volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  bitcoin:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/datadrive/bitcoin'

  # lightening daemon [lnd]
  lnd:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/datadrive/lnd'

  bitcoind:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/datadrive/bitcoind'

  rtl:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/datadrive/rtl'

      