version: '2'

services:

    # btc is an image of bitcoin node which used as base image for btcd and
    # btccli. The environment variables default values determined on stage of
    # container start within starting script.
    btc:
      image: btcd
      build:
        context: btcd/
      volumes:
            - shared:/rpc
            - bitcoin:/data
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK

    btcd:
        extends: btc
        container_name: btcd
        environment:
          - DEBUG
          - MINING_ADDRESS
        entrypoint: ["./start-btcd.sh"]

    btcctl:
        extends: btc
        container_name: btcctl
        links:
            - "btcd:rpcserver"
        entrypoint: ["./start-btcctl.sh"]

    #
    # lnd - lightening daemon
    # 

    lnd:
        image: lnd
        container_name: lnd
        build:
          context: ../
          dockerfile: docker/lnd/Dockerfile
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG
        volumes:
            - shared:/rpc
            - lnd:/root/.lnd
        links:
          - "btcd:blockchain"
        ports:
           - "8089:8089"
           - "10001:10001"
        expose:
          - "8089"
          - "10001"
        entrypoint: ["./start-lnd.sh"]
  

    nodeapp:
        image: nodeapp
        container_name: nodeapp
        build:
          context: nodeapp/
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG
        volumes:
            - shared:/rpc
            - lnd:/root/.lnd
        # HOST:CONTAINER
        ports:
           - "8088:8088"
        links:
          - lnd
        # expose only works in containers networks; not visible from host
        # expose:
        #  - "8088"

volumes:
  # shared volume is need to store the btcd rpc certificates and use it within
  # btcctl and lnd containers.
  shared:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/run/media/florian/ZEUS_USBG3_1TERRA/shared'

  # bitcoin volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  bitcoin:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/run/media/florian/ZEUS_USBG3_1TERRA/bitcoin'


  # lightening daemon [c-lightening]
  lightning:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/run/media/florian/ZEUS_USBG3_1TERRA/lightening'

  # lightening daemon [lnd]
  lnd:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/run/media/florian/ZEUS_USBG3_1TERRA/lnd'